### ISSUE TITLE
Flo Tools no longer working with Pro Tools?

### ISSUE THREAD

**Issue by SitedBlind** [flotools/flotools#9]
Flo Tools was working completely fine with Pro Tools until last week it stopped operating out of the blue. I'm on macOS Sierra using flotools-2.3.2, Pro Tools Version 11.3.2, and Keyboard Maestro 8.2.4. I've followed all of the instructions from the Getting Started page on the Flo Tools website. When I quit Pro Tools I still get the message Keyboard Maestro Engine Macro Cancelled Cancel All Macros which I always got when it was working so the macros must be passing through to a point, but very confused why they still don't seem to be working in Pro Tools. Any help would be greatly appreciated thanks.

**Comment by rfiorentino1** [comment]
Did you update your OS at all? Both Pro Tools and FloTools versions that you're using are pretty old, so you may want to update everything in general, but if you really want to stay on your current versions, email me at rocco@musicbyrocco.com and I will try and help you as much as I can. I'm closing this issue for now because it is not directly related to a flotools Bug
